### ISSUE TITLE
Windows version 6 14 0 doesn't start

### ISSUE THREAD

**Issue by choupette-change** [f4exb/sdrangel#924] opened 2021-06-15 12:05 UTC
the windows version 6 14 0 does not start ... the launch process is interrupted ???
![image](https://user-images.githubusercontent.com/68333247/122048911-23b06d80-cde2-11eb-8be9-69974f62ed12.png)

**Comment by srcejon** [comment] 2021-06-15 14:04
What's in the log file?

**Comment by choupette-change** [comment] 2021-06-15 14:54
i haven't changed anything from the previous version, i just uninstalled it and reinstalled 6 14 0, where is the log file?

**Comment by srcejon** [comment] 2021-06-15 16:05
See Preferences > Logging menu

Usually in c:\Users\you\sdrangel.log

**Comment by choupette-change** [comment] 2021-06-15 20:32
i can't open V6 14 0 so i have no log file. I just retested the V 6 13 it's ok for me ...

**Comment by f4exb** [comment] 2021-06-16 04:52
If you set up the log file in v6.13 these settings will be persistent anyway when you upgrade to v6.14. As the issue is not trivially reproducible we need more information to investigate the issue further.

**Comment by choupette-change** [comment] 2021-06-16 10:55
[sdrangel.log](https://github.com/f4exb/sdrangel/files/6662424/sdrangel.log)

**Comment by f4exb** [comment] 2021-06-16 11:35
This is the log from the 6.13.0 version and I do not understand why `DeviceAPI::loadSamplingDeviceSettings` call happens 3 times. However I see the AIS demod is in the default preset therefore it gets loaded at startup time. There is an issue in 6.14.0 with AIS demod already reported in #925 and this may very well be the issue here.

Can you try with the latest version from master. There is an installer directly accessible from Appveyor here: https://ci.appveyor.com/project/f4exb/sdrangel/builds/39618839/job/9r81isna2rm3b6ms/artifacts

**Comment by choupette-change** [comment] 2021-06-16 12:22
it works with the link above (master); I attach you the last log file created
[sdrangel.log](https://github.com/f4exb/sdrangel/files/6662936/sdrangel.log)

**Comment by f4exb** [comment] 2021-06-23 06:44
ok then it is fixed with #925

**Closed by f4exb** 2021-06-23 06:44 UTC
