### ISSUE TITLE
can't save settings

### ISSUE THREAD

**Issue by drom** [f4exb/sdrangel#391] opened 2019-07-27 08:51 UTC
Setting SDRangle on the PlutoSDR box, with R0/T1, SSB demodulator/modulator, window sizes, locations, etc.
I can't find a way to store my settings and I have to set up it again after every restart.
Presets can store some R0 settings, but I am losing T1 settings for sure.

**Comment by f4exb** [comment] 2019-07-27 20:22
This is no possible by design sorry.

**Comment by f4exb** [comment] 2019-07-28 08:56
This can be worked around with the rest API. See:
https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/config.py
and
https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/examples/test.json

**Comment by f4exb** [comment] 2019-07-31 06:29
I suppose this workaround is OK hence closing the issue

**Closed by f4exb** 2019-07-31 06:29 UTC
