### ISSUE TITLE
Segmentation Fault when closing ADS-B panel while Sampling Device is still running

### ISSUE THREAD

**Issue by ChiefGokhlayeh** [f4exb/sdrangel#915] opened 2021-06-04 22:23 UTC
I noticed a segmentation fault whenever closing the ADS-B Demodulator panel while having the sampling device still running.

Steps to reproduce:

1) Open sdrangel
2) Select "Sampling Device" `TestSource`
3) Add ADS-B Demodulator to Channels
4) Start `TestSource`
5) Close ADS-B Demodulator panel without stopping `TestSource`

If `TestSource` is stopped before closing ADS-B Demodulator everything continues to work fine.

I traced the issue down to an ~"use-after-delete"~ "use-after-_half_-delete" by `DSPDeviceSourceEngine`:
https://github.com/f4exb/sdrangel/blob/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d/sdrbase/dsp/dspdevicesourceengine.cpp#L595-L597

In this case `sink` is the already _half_ deleted [`ADSBDemod`](https://github.com/f4exb/sdrangel/blob/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d/plugins/channelrx/demodadsb/adsbdemod.cpp#L124-L130) object. The `delete` is called before that by `DeviceUISet::handleChannelGUIClosing()` on UI-thread:
https://github.com/f4exb/sdrangel/blob/de23efe635043867b914faa2977228e0780d4121/sdrgui/device/deviceuiset.cpp#L439

-- Tested on [latest master](https://github.com/f4exb/sdrangel/commit/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d) following v6.13.0.

**Comment by ChiefGokhlayeh** [comment] 2021-06-04 23:12
It appears this use-after-delete isn't unique to ADS-B Demod. I found the same fault-type (`sink->stop();` being called after `sink` already got deleted) in other plugins, such as Broadcast FM or AM Demodulator.

**Comment by f4exb** [comment] 2021-06-05 04:51
The issue is that `ADSBDemod::stop` is called several times. When the demod is closed via GUI there is no other way to do this than through the `ChannelGUI::closeEvent`. However `DSPDeviceSourceEngine::removeSink` also calls  `ADSBDemod::stop` which is legitimate. This is the sequence of events shown in the log right before the crash:

```
2021-06-05 06:43:25.054 (D) ChannelGUI::closeEvent                                                                                                                                                                                          
2021-06-05 06:43:25.054 (D) ADSBDemod::stop                                                                                                                                                                                                 
2021-06-05 06:43:25.054 (D) ADSBDemodSink::stopWorker: Stopping worker                                                                                                                                                                      
2021-06-05 06:43:25.061 (D) ADSBDemodSink::stopWorker: Worker stopped                                                                                                                                                                       
2021-06-05 06:43:25.062 (D) DSPDeviceSourceEngine::removeSink:  ADSBDemod                                                                                                                                                                   
2021-06-05 06:43:25.062 (D) DSPDeviceSourceEngine::handleSynchronousMessages:  DSPRemoveBasebandSampleSink                                                                                                                                  
2021-06-05 06:43:25.062 (D) ADSBDemod::stop                                                                                                                                                                                                 
2021-06-05 06:43:25.062 (W) QObject::disconnect: No such signal QObject::messageEnqueued()                                                                                                                                                  
Segmentation fault (core dumped)
```
This yields the last warning message that looks inconsistent because `MessageQueue` does have a `MessageEnqueued()` signal. But in fact this comes from the fact that this signal was already disconnected.

In fact `ADSBDemodSink::stopWork` should handle the condition whether it is running or not. Rewriting it like this solves the problem:

```c++
void ADSBDemodWorker::stopWork()
{
    QMutexLocker mutexLocker(&m_mutex);

    if (!m_running) {
        return;
    }

    m_heartbeatTimer.stop();
    disconnect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
    m_running = false;
}
```

**Comment by f4exb** [comment] 2021-06-05 05:03
Note: `m_basebandSink->stopWork` is also called twice in `ADSBDemod::stop` which in turns calls `ADSBDemodSink::stopWorker` twice. However in this case the running condition is handled properly:

```c++
void ADSBDemodSink::stopWorker()
{
    if (m_worker.isRunning())
    {
        qDebug() << "ADSBDemodSink::stopWorker: Stopping worker";
        m_worker.requestInterruption();
        // Worker may be blocked waiting for a buffer
        for (int i = 0; i < m_buffers; i++)
        {
            if (m_bufferRead[i].available() == 0)
                m_bufferRead[i].release(1);
        }
        m_worker.wait();
        // If this is called from ADSBDemod, we need to also
        // make sure baseband sink thread isnt blocked in processOneSample
        for (int i = 0; i < m_buffers; i++)
        {
            if (m_bufferWrite[i].available() == 0)
                m_bufferWrite[i].release(1);
        }
        qDebug() << "ADSBDemodSink::stopWorker: Worker stopped";
    }
}
```

**Closed** 2021-06-05 05:17 UTC
