### ISSUE TITLE
BP not working 

### ISSUE THREAD

**Issue by countryboy057** [f4exb/sdrangel#574] opened 2020-07-17 23:48 UTC
Hello 

I have installed the latest releases on both Windows and linux and neither are allowing BP to be decoded. Regular dmr works fine but BP is not. I have tried two different frequencies where I know the BP key.

How can I help troubleshoot this ?

**Comment by f4exb** [comment] 2020-07-18 02:32
BP is supposed to be implemented as per Motorola specs however I have no way to test this nor correct the codes if anything is wrong. The codes appear here (it isn dsdcc): https://github.com/f4exb/dsdcc/blob/master/dmr.cpp#L102 and is appliede here: https://github.com/f4exb/dsdcc/blob/master/dmr.cpp#L639

The full diff of the commit is here: https://github.com/f4exb/dsdcc/commit/9889e6a4f531650e55334e9e2c0312856b763a96 but also contains some cosmetic changes.

**Comment by countryboy057** [comment] 2020-07-18 19:19
I will get you a sample and upload it sometime today! Thank you!

**Comment by countryboy057** [comment] 2020-07-18 19:49
What is your email address? Id like to send the link to you that way.

**Comment by f4exb** [comment] 2020-07-19 05:19
please use f4exb06@free.fr

**Comment by f4exb** [comment] 2020-07-21 11:52
I have tried many variants in case of endianess mismatch or wrong lsb or msb first issue but none of the attempts leads to something intelligible. So the algorithm implemented is plain wrong and I have no way to correct this.

The solution is to remove this future in the next revision.

**Comment by countryboy057** [comment] 2020-07-21 11:56
There is another gentlemen that has implemented it . Maybe his code can
help ?

https://twitter.com/LouisErigHerve

His guthub

https://github.com/LouisErigHerve/dsd

I am a network admin and not very good with coding but am willing to help
if you ever need things tested and such

**Comment by f4exb** [comment] 2020-07-21 12:01
Thanks for the pointer that's interesting and seems quite different from my initial implementation.

**Comment by countryboy057** [comment] 2020-07-21 12:08
No problem. Thank your time in sdrangel and dsdcc. They are excellent
programs that I use dailey here.

**Comment by f4exb** [comment] 2020-07-21 12:11
Well checked the code of Louis Erig Herve but it is pretty empty. There are just comments on how things should work but no details on how those 882 bits (6*3*49) bits should be filled. Unfortunately this means I cannot carry on and will not support any kind of encryption in any way for any mode.

**Comment by countryboy057** [comment] 2020-07-21 12:16
I understand. I know there was some other documents out there also. I will
see if I can find them

**Comment by countryboy057** [comment] 2020-07-21 12:18
Here is a screenshot of somethings he was working on.

[image: image.png]

**Comment by countryboy057** [comment] 2020-07-21 12:18
[image: image.png]

**Comment by countryboy057** [comment] 2020-07-21 12:19
[image: image.png]

**Comment by f4exb** [comment] 2020-07-21 12:49
Maybe I overlooked the Twitter link it seems to contain much more information...

**Comment by f4exb** [comment] 2020-07-21 17:56
Well even like this it doesn't work.

**Comment by countryboy057** [comment] 2020-07-21 17:59
I was looking through your code. For the privacy keys.I am wondering if they need the 0x in front of them. The list I have for the keys just shows 4 hex characters.

**Comment by f4exb** [comment] 2020-07-22 08:15
`0x` prefix is the way in C/C++ (probably some other languages as well) to tell the compiler that what comes next are hexadecimal characters.

The issue is that the algorithm does not work for a reason I don't know and I don't want to dig more into this. I know people are excited about privacy codes well I am not.

**Comment by countryboy057** [comment] 2020-07-22 16:01
Could you share what you have redone and let me play around with it ? I
would like to learn more

**Comment by TheDefender44** [comment] 2020-07-23 00:15
> 
> 
> Thanks for the pointer that's interesting and seems quite different from my initial implementation.

I believe it is in part because his initial, non-public version includes auto-detection of the BP keys. That's why part of it is empty and/or quite different from your first implementation.

**Comment by f4exb** [comment] 2020-07-23 11:49
@countryboy057 the actual code is in dsdcc https://github.com/f4exb/dsdcc I have committed my latest changes to apply the XORing of bits only to the 49 data bits of the AMBE frame.

**Comment by f4exb** [comment] 2020-08-01 08:43
Now removed in v4.14.19

**Closed by f4exb** 2020-08-01 08:43 UTC
