### ISSUE TITLE
Use Pulseaudio as a Souce for High Sampling Rate Soundcards

### ISSUE THREAD

**Issue by goatmanic** [f4exb/sdrangel#505] opened 2020-04-18 20:10 UTC
I’d like to build a ELF /  VLF antenna for use with my 192KHz, 24 bit ADC. Pulseaudio as a source would be awesome to start viewing and recording nature’s low frequency band.  Thanks!

**Comment by f4exb** [comment] 2020-04-19 08:11
Duplicate of #496

**Closed by f4exb** 2020-04-19 08:11 UTC
