### ISSUE TITLE
Confirmed New Versions are buggy.

### ISSUE THREAD

**Issue by Ghaz75** [f4exb/sdrangel#816] opened 2021-03-26 19:12 UTC
I confirm that the latest and the previous versions both are buggy. I use SDRAngel for my research, My hackrf and rtl-sdr work fine on version 4.14.17. But ever since I have used latest two versions. The app crashes while loading HackRF as sink device. It sometimes works when I load RTL-SDR as Source device first and then HackRF as Sink Device. It might be because of that I am using a USB power hub for both the devices. as stop playing one device also crashes the other  in SDRAngel. BUT...... in version 4.14.17 they all are working fine without any problem even through USB power Hub. My OS is Windows 10 Home 64 bit. latest update.

**Comment by f4exb** [comment] 2021-03-29 15:34
Duplicate of https://github.com/f4exb/sdrangel/issues/718

**Closed by f4exb** 2021-03-29 15:34 UTC
