### ISSUE TITLE
Using older version 5.1.0 of SWGDeviceSetApi (Qt5)

### ISSUE THREAD

**Issue by aonez** [f4exb/sdrangel#490] opened 2020-03-22 10:09 UTC
Not sure what you're using locally but from the source download the older version lower cased `SWGDevicesetApi` is used instead of the newer 5.3.0 upper case `SWGDeviceSetApi` version.

Reported by @loewal here: https://github.com/aonez/Keka/issues/527

**Comment by f4exb** [comment] 2020-03-25 21:05
Duplicate of #491

**Closed by f4exb** 2020-03-25 21:05 UTC
