### ISSUE TITLE
Please we look for QO-100 DVBS2 decoder support on sdrangel any news ? 

### ISSUE THREAD

**Issue by khanfar** [f4exb/sdrangel#333] opened 2019-05-02 20:37 UTC

**Comment by khanfar** [comment] 2019-05-02 20:38
may be this software can help to catch something to add in sdrangel 
http://www.pabr.org/radio/leandvb/leandvb.en.html#

**Comment by khanfar** [comment] 2019-05-02 20:40
and this too :
https://github.com/pabr/xdsopl-LDPC-pabr

**Comment by f4exb** [comment] 2019-05-02 22:54
leandvb is already used in the DATV Demod plugin. I think it implements LDPC internally so there should not be a need for something specific for LDPC.

Closing this one as dupe of #299

**Closed by f4exb** 2019-05-02 22:54 UTC
