### ISSUE TITLE
WFM Demodulator plugin crashes in 3.8.0 if opened after source streaming is started

### ISSUE THREAD

**Issue by texasyojimbo** [f4exb/sdrangel#91] opened 2017-11-05 22:45 UTC
Version: 3.8.0
Platform: Windows 10
Source: LimeSDR

Steps to reproduce:

1. Open sdrangel
2. For R0 source, set up device as LimeSDR channel 0
3. Start streaming from device
4. Try to add WFM demodulator plugin

**Comment by texasyojimbo** [comment] 2017-11-05 23:07
Issue replicated in 3.8.1.

**Comment by f4exb** [comment] 2017-11-06 01:15
This is a dupe of #88

**Comment by f4exb** [comment] 2017-11-09 22:07
Fixed in v3.8.2

**Closed by f4exb** 2017-11-09 22:07 UTC
Labels: duplicate
